Homework 13
Otus-DevOps-2017-11/nefariusmag_infra pull request #10
Opened 2018-01-24 11:14 UTC by Nefariusmag

Vagrant и Molecule для локальной разработки и тестирования.

2018-01-24 12:44 UTC, Nklya requested changes
Добрый день.

Дмитрий, почти все относительно нормально, за исключением не сделанного задания по использованию ансибла в пакере, слайд 61.

2018-01-24 12:44 UTC, Nklya commented on ansible/old/app.json
>      "image_family": "reddit-app-base",
И как сюда попал шаблон пакера?

2018-01-24 12:44 UTC, Nklya commented on packer/db.json
>      "image_family": "reddit-db-base",
С чего вдруг в шаблонах пакера обратно оказались баш скрипты, если в 11 переходили на ансибл?

2018-01-25 19:34 UTC, Nefariusmag commented on ansible/old/app.json
>      "image_family": "reddit-app-base",
Я понял задание что надо создать app.json и db.json с ansible, но я не видел фразы что создать их надо в папке packer (на слайде 61 про папку нету ни слова), создал в той что работали ansible, а затем перетащил в ansible\old

Пакер работающий через ansible скрипты есть и работает отлично.

2018-01-25 19:40 UTC, Nefariusmag commented on packer/db.json
>      "image_family": "reddit-db-base",
Так как актуальные скрипты в папке ansible/old а это старые

2018-01-25 19:51 UTC, Nklya commented on ansible/old/app.json
>      "image_family": "reddit-app-base",
Специально для тебя добавлю.

2018-01-25 19:51 UTC, Nklya requested changes
В папке packer должны быть шаблоны пакера для app db, использующие ансибл роли.

2018-01-25 19:53 UTC, Nefariusmag commented on ansible/old/app.json
>      "image_family": "reddit-app-base",
Оке, я завтра сделаю чтобы всё нормально было

2018-01-26 09:32 UTC, Nklya approved these changes
Да, теперь все выполнено нормально.

2018-01-26 09:32 UTC, Nklya commented on packer/app.json
> +      "playbook_file": "../ansible/playbooks/packer_app.yml"
А можно было билдить из корня репы и не было бы таких странных путей.

2018-01-26 16:51 UTC, merged

2018-01-26 16:53 UTC, Nefariusmag commented on packer/app.json
> +      "playbook_file": "../ansible/playbooks/packer_app.yml"
хм... о! надо подумать как сделать так, чтобы он не зависел от того из какой папки запускаешь!

2018-01-26 17:11 UTC, Nklya commented on packer/app.json
> +      "playbook_file": "../ansible/playbooks/packer_app.yml"
Можно добавить аналогично просто `{{ pwd }}`  перед именем плейбука.
Я вообще писал про то, что вот такое `..` не очень.